[package]
name = "giga-segy-in"
version = "0.2.0"
authors = ["Aleksey Zholobenko <aleksey.zholobenko@giga-infosystems.com>"]
edition = "2018"

[lib]
name = "giga_segy_in"
crate-type = ["staticlib","rlib"]

[dependencies]
giga-segy-core = { path = "../giga-segy-core" }

encoding8 = "0.3"
memmap = "0.6"
num = "0.2"

[features]
default = []
to_json = ["giga-segy-core/to_json"]